language: python

addons:
  apt:
    packages:
      - gfortran  # scipy
      - libblas-dev  # scipy
      - liblapack-dev  # scipy
      - swig  # m2crypto

matrix:
  include:
    - python: 2.6
      env: PRE=""
    - python: 2.7
      env: PRE=""
    - python: 2.7
      env: PRE="--pre" GWPY="git+https://github.com/gwpy/gwpy.git"
  allow_failures:
    - python: 2.7
      env: PRE="--pre" GWPY="git+https://github.com/gwpy/gwpy.git"

before_install:
  - pip install -q --upgrade pip
  # install specific packages for python2.6
  - if [[ ${TRAVIS_PYTHON_VERSION} == '2.6' ]]; then pip install "scipy<0.18" "astropy<1.2"; fi
  - pip install ${PRE} -r requirements.txt

install:
  - pip install .

script:
  - pip install ${PRE} unittest2 coveralls "pytest>=2.8"
  - coverage run --source=hveto --omit="hveto/tests/*,hveto/_version.py" ./setup.py test
  - coverage run --append --source=hveto --omit="hveto/tests/*,hveto/_version.py" `which hveto` --help

after_success:
  - coveralls

cache:
  apt: true
  pip: true
