language: python

matrix:
  fast_finish: true

  include:
    - python: '2.7'
      env: PIP_FLAGS="--quiet --pre"
    - python: '3.5'
      env: PIP_FLAGS="--quiet --pre"
    - python: '3.6'
      env: PIP_FLAGS="--quiet --pre"
    - python: '3.7'
      dist: xenial
      sudo: required
      env: PIP_FLAGS="--quiet --pre"

    - python: '2.7'
      env: PIP_FLAGS="--quiet"
    - python: '3.5'
      env: PIP_FLAGS="--quiet"
    - python: '3.6'
      env: PIP_FLAGS="--quiet"
    - python: '3.7'
      dist: xenial
      sudo: required
      env: PIP_FLAGS="--quiet"

before_install:
  - python -m pip install -q --upgrade pip
  - python -m pip install lalsuite  # to get LAL
  - python -m pip install ${PIP_FLAGS} -r requirements.txt

install:
  # note: need --editable for coverage with `which ...` to work
  - python -m pip install --editable .

script:
  - python -m pip install ${PIP_FLAGS} unittest2 coveralls "pytest>=2.8"
  - coverage run ./setup.py test
  - coverage run --append `which hveto` --help
  - coverage run --append `which hveto-cache-events` --help
  - coverage run --append `which hveto-trace` --help

after_success:
  - coveralls

cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
