language: python

os: linux

matrix:
  fast_finish: true

  include:
    # conda builds
    - name: "conda:3.6"
      env: PYTHON_VERSION="3.6"
    - name: "conda:3.7"
      env: PYTHON_VERSION="3.7"
    - name: "conda:3.8"
      env: PYTHON_VERSION="3.8"


install:
  # install miniconda, create env, and activate
  - bash -ex ./ci/install-conda.sh
  # install this package
  # note: need --editable for coverage with `which ...` to work
  - python -m pip install --editable .

script:
  - python -m flake8 .
  - python -m flake8 bin/*
  - python -m coverage run -m pytest hveto/
  - python -m coverage run --append `which hveto` --help
  - python -m coverage run --append `which hveto-cache-events` --help
  - python -m coverage run --append `which hveto-trace` --help

after_success:
  - bash -ex ./ci/codecov.sh

cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
