language: python

os: linux

matrix:
  fast_finish: true

  include:
    # conda builds
    - name: "conda:3.6"
      env: PYTHON_VERSION="3.6"
    - name: "conda:3.7"
      env: PYTHON_VERSION="3.7"
    - name: "conda:3.8"
      env: PYTHON_VERSION="3.8"


install:
  # install miniconda, create env, and activate
  - bash -ex ./ci/install-conda.sh

script:  # run tests
  - bash -ex ./ci/test.sh

after_success:  # compute coverage
  - bash -ex ./ci/codecov.sh

cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
