language: python

addons:
  apt:
    sources:
      - sourceline: deb http://software.ligo.org/lscsoft/debian wheezy contrib
        key_url: http://software.ligo.org/keys/deb/lscsoft.key
      - sourceline: deb-src http://software.ligo.org/lscsoft/debian wheezy contrib
        key_url: http://software.ligo.org/keys/deb/lscsoft.key
    packages:
      - gfortran  # scipy
      - libblas-dev  # scipy
      - liblapack-dev  # scipy
      - swig  # m2crypto
      - pkg-config  # lal
      - zlib1g-dev  # lal
      - libgsl0-dev  # lal
      - swig  # lal
      - bc  # lal
      - libfftw3-dev  # lal

python:
  - '2.6'
  - '2.7'
  - '3.5'

env:
  global:
    - LAL_VERSION="6.18.0"
  matrix:
    - PIP_FLAGS="--quiet"
    - PIP_FLAGS="--quiet --pre"

matrix:
  exclude:
    - python: '2.6'
      env: PIP_FLAGS="--quiet --pre"
  allow_failures:
    - python: '2.6'
    - python: '3.5'
  fast_finish: true

before_install:
  - pip install -q --upgrade pip
  # install specific packages for python2.6
  - if [[ ${TRAVIS_PYTHON_VERSION} == '2.6' ]]; then pip install "scipy<0.18" "astropy<1.2" "matplotlib<2.0"; fi
  - pip install ${PRE} -r requirements.txt
  - .travis/build-lal.sh

install:
  # note: need --editable for coverage with `which ...` to work
  - pip install --editable .

script:
  - pip install ${PRE} unittest2 coveralls "pytest>=2.8"
  - coverage run ./setup.py test
  - coverage run --append `which hveto` --help
  - coverage run --append `which hveto-cache-events` --help
  - coverage run --append `which hveto-trace` --help

after_success:
  - coveralls

cache:
  apt: true
  pip: true
  directories:
    - lal-${LAL_VERSION}
